### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by AlexanderWilfing** [Hanslick-Online/hsl-vms-data#4]
Please change "Concorance" "Concordance," or, even better, to "Konkordanz" in the treatise's comparison feature (e.g. https://hanslick.acdh.oeaw.ac.at/diff_1.18.html), since the edition is in German.

**Comment by linxOD** [comment]
6a1427eb5133753e530f35da3563c8743a801080

**Comment by linxOD** [comment]
https://hanslick-online.github.io/hsl-app-dev/diff_1.18.html

**Comment by AlexanderWilfing** [comment]
Cheers!
